env:
  global:
   - secure: "E1iOs3Ag9oM8tXTTPSE35IwSxrrRgCew51b8JdyNjpptyFvDBNPCPDkA9OA4NKCIQ1/bZyliKIl3oOX6wejDGabAD7jPi2dIh7BK87aWSpyakKiDNL1kq79c/dP8h9L52mb19VgWQCsPQIwovFxIFPiIAQBBFhkNRjrd1Y98bGI="

compiler: gcc
language: c

env:
  - DEFINES=""
  - DEFINES="CPPFLAGS=-DTGRUB_HP_WORKAROUND"
  - DEFINES="CPPFLAGS=-DTGRUB_DEBUG"

script:
  - "./autogen.sh"
  - "./configure --target=i386 -with-platform=pc"
  - "echo ${DEFINES}"
  - "make ${DEFINES} -j 4 --silent"

os:
  - linux

notifications:
  email:
    recipients:
      - daniel@neus-online.eu

addons:
  coverity_scan:
    project:
      name: "Sirrix-AG/TrustedGRUB2"
      description: "Build submitted via Travis CI"
    notification_email: daniel@neus-online.eu
    build_command_prepend: "./autogen.sh;./configure --target=i386 -with-platform=pc; make clean"
    build_command:   "make -j 4 --silent"
    branch_pattern: coverity_scan
